name: Docker Container Metrics

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: upload linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: uploads
        path: target/release/docker-container-metrics
        if-no-files-found: error